# Generated by Django 4.2.1 on 2023-05-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FittingNeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.IntegerField()),
                ('type', models.CharField(choices=[('male', 'Папа'), ('female', 'Мама')], max_length=10)),
                ('fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pik.fitting')),
            ],
        ),
    ]
