version: '3.9'

services:

  django:
    container_name: pik_django
    build: ./django
    ports:
      - '8000:8000'
    volumes:
      - ../:/app
    command: python manage.py runserver 0.0.0.0:8000
